---
__snmp_packages:
  - 'snmpd'
  - 'snmp'
__snmp_service_name: 'snmpd'
__snmp_config_dir: '/etc/snmp'
__snmp_config_file: '/etc/snmp/snmpd.conf'
__snmp_persistent_dir: '/var/lib/snmp'
__snmp_apparmor_profile: 'usr.sbin.snmpd'
