---
- name: Service | Deploy systemd service unit
  ansible.builtin.template:
    src: lynis-audit.service.j2
    dest: '/etc/systemd/system/lynis-audit.service'
    owner: root
    group: root
    mode: '0644'
  when:
    - lynis_enabled | bool
    - lynis_timer_enabled | bool
  notify: Reload systemd daemon (lynis)

- name: Service | Deploy systemd timer unit
  ansible.builtin.template:
    src: lynis-audit.timer.j2
    dest: '/etc/systemd/system/lynis-audit.timer'
    owner: root
    group: root
    mode: '0644'
  when:
    - lynis_enabled | bool
    - lynis_timer_enabled | bool
  notify:
    - Reload systemd daemon (lynis)
    - Restart lynis timer

- name: Service | Enable and start lynis timer
  ansible.builtin.systemd:
    name: lynis-audit.timer
    enabled: true
    state: started
    daemon_reload: true
  when:
    - lynis_enabled | bool
    - lynis_timer_enabled | bool

- name: Service | Disable and stop lynis timer
  ansible.builtin.systemd:
    name: lynis-audit.timer
    enabled: false
    state: stopped
  when:
    - lynis_enabled | bool
    - not (lynis_timer_enabled | bool)
  failed_when: false
