---
- name: Reload NetworkManager connections
  ansible.builtin.command:
    cmd: nmcli connection reload
  changed_when: false
  when: networkmanager_enabled | bool

- name: Restart NetworkManager
  ansible.builtin.systemd_service:
    name: '{{ __networkmanager_service_name }}'
    state: restarted
  when: networkmanager_service_enabled | bool

- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart polkitd
  ansible.builtin.systemd_service:
    name: '{{ __networkmanager_polkit_service }}'
    state: restarted
  when: networkmanager_polkit_enabled | bool
