---
- name: Firewall | Check if firewalld is running
  ansible.builtin.systemd_service:
    name: firewalld
  register: __snmp_firewalld_status
  failed_when: false

- name: Firewall | Manage SNMP firewall rule
  ansible.posix.firewalld:
    service: snmp
    zone: '{{ snmp_firewalld_zone }}'
    permanent: true
    immediate: true
    state: "{{ snmp_firewalld_enabled | bool | ternary('enabled', 'disabled') }}"
  when: __snmp_firewalld_status.status.ActiveState | default('') == 'active'
