---
- name: Service | Manage SNMP service
  ansible.builtin.systemd_service:
    name: '{{ __snmp_service_name }}'
    enabled: "{{ snmp_service_enabled | bool }}"
    state: "{{ snmp_service_enabled | bool | ternary('started', 'stopped') }}"
    daemon_reload: true
