---
# =============================================================================
# rkhunter - Installation Tasks
# =============================================================================

- name: Install | rkhunter package
  ansible.builtin.package:
    name: '{{ __rkhunter_package }}'
    state: present

- name: Install | Ensure rkhunter directories exist
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop:
    - '/var/lib/rkhunter/db'
    - '/var/lib/rkhunter/tmp'
