---
#
# System Monitors
#

__utils_monitor_htop: 'htop'
__utils_monitor_btop: 'btop'
__utils_monitor_bottom: ''
__utils_monitor_atop: 'atop'

#
# Terminal Multiplexers
#

__utils_mux_tmux: 'tmux'
__utils_mux_zellij: ''
__utils_mux_screen: 'screen'

#
# File Transfer
#

__utils_transfer_rsync: 'rsync'

#
# Search Tools
#

__utils_search_ripgrep: 'ripgrep'
__utils_search_fd: 'fd-find'

#
# System Info (Fetch Tools)
#

__utils_fetch_fastfetch: 'fastfetch'
__utils_fetch_hyfetch: ''
__utils_fetch_archey4: ''
__utils_fetch_cpufetch: ''

#
# Fun Tools
#

__utils_fun_cowsay: 'cowsay'
__utils_fun_fortune: 'fortune-mod'
__utils_fun_lolcat: ''
__utils_fun_ponysay: ''
__utils_fun_figlet: 'figlet'
__utils_fun_toilet: 'toilet'
__utils_fun_sl: 'sl'
__utils_fun_cmatrix: ''
__utils_fun_cbonsai: ''
__utils_fun_asciiquarium: ''
__utils_fun_nyancat: ''
__utils_fun_no_more_secrets: ''
__utils_fun_tty_clock: ''
__utils_fun_pipes: ''
__utils_fun_pokemon_colorscripts: ''
__utils_fun_pokemonsay: ''
__utils_fun_hollywood: ''
