---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    fonts_enabled: true
    fonts_base: true
    fonts_dejavu: true
    fonts_liberation: true
    fonts_noto: true
    fonts_noto_emoji: true
    fonts_noto_cjk: false
    fonts_coding: true
    fonts_coding_families:
      - 'firacode'
    fonts_nerd: "{{ ansible_facts['os_family'] == 'Archlinux' }}"
    fonts_nerd_families:
      - 'symbols-only'
    fonts_fontconfig_enabled: true
    fonts_fontconfig_antialias: true
    fonts_fontconfig_hinting: 'hintslight'
    fonts_fontconfig_subpixel: 'rgb'
    fonts_fontconfig_lcdfilter: 'default'

  tasks:
    - name: Converge | Include fonts role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
