---
- name: Main | Load OS-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      paths:
        - 'vars'
  tags: [clamav]

- name: Main | Import install tasks
  ansible.builtin.import_tasks: install.yml
  tags: [clamav, clamav:install]

- name: Main | Include BTRFS tasks
  ansible.builtin.include_tasks:
    file: btrfs.yml
    apply:
      tags: [clamav, clamav:configure]
  when: clamav_enabled | bool
  tags: [clamav, clamav:configure]

- name: Main | Import configure tasks
  ansible.builtin.import_tasks: configure.yml
  tags: [clamav, clamav:configure]

- name: Main | Import service tasks
  ansible.builtin.import_tasks: service.yml
  tags: [clamav, clamav:service]

- name: Main | Include firewall tasks
  ansible.builtin.include_tasks:
    file: firewall.yml
    apply:
      tags: [clamav, clamav:firewall]
  when: clamav_firewalld_enabled | default(false) | bool
  tags: [clamav, clamav:firewall]

- name: Main | Include AppArmor tasks
  ansible.builtin.include_tasks:
    file: apparmor.yml
    apply:
      tags: [clamav, clamav:apparmor]
  when:
    - clamav_apparmor_enabled | default(false) | bool
    - ansible_facts['os_family'] != 'RedHat'
  tags: [clamav, clamav:apparmor]
