---
galaxy_info:
  author: Marc Straube
  description: Manage systemd-resolved DNS resolver
  license: MIT
  min_ansible_version: '2.17'

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - all

  galaxy_tags:
    - resolved
    - dns
    - systemd
    - system

dependencies: []
