---
- name: Nano | Deploy global configuration
  ansible.builtin.template:
    src: nanorc.j2
    dest: '{{ __editors_nano_config_global }}'
    owner: root
    group: root
    mode: '0644'
    backup: true
