---
# =============================================================================
# Neovim Configuration
# =============================================================================

- name: Neovim | Ensure global config directory exists
  ansible.builtin.file:
    path: '/etc/xdg/nvim'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Neovim | Deploy global configuration
  ansible.builtin.template:
    src: init.vim.j2
    dest: '{{ __editors_neovim_config_global }}'
    owner: root
    group: root
    mode: '0644'
