---
- name: Neovim | Ensure global config directory exists
  ansible.builtin.file:
    path: '{{ __editors_neovim_config_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Neovim | Deploy global configuration
  ansible.builtin.template:
    src: init.vim.j2
    dest: '{{ __editors_neovim_config_file }}'
    owner: root
    group: root
    mode: '0644'
