---
- name: Vim | Deploy global configuration
  ansible.builtin.template:
    src: vimrc.j2
    dest: '{{ __editors_vim_config_global }}'
    owner: root
    group: root
    mode: '0644'
    backup: true
