---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    sysctl_enabled: true
    sysctl_profile_security_enabled: true
    sysctl_profile_network_performance_enabled: true
    sysctl_profile_database_enabled: false
    sysctl_profile_webserver_enabled: false
    sysctl_profile_docker_enabled: false
    sysctl_parameters:
      vm.swappiness: 10
      net.core.somaxconn: 1024
    sysctl_apply_immediately: true

  tasks:
    - name: Converge | Include sysctl role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
