---
- name: Database | Set database paths based on format
  ansible.builtin.set_fact:
    __aide_db_path: >-
      {{ aide_database }}{{ '.gz' if aide_database_format == 'gzip' else '' }}
    __aide_db_new_path: >-
      {{ aide_database_new }}{{ '.gz' if aide_database_format == 'gzip' else '' }}

- name: Database | Check if AIDE database exists
  ansible.builtin.stat:
    path: '{{ __aide_db_path }}'
  register: aide_db_check

- name: Database | Initialize AIDE database
  ansible.builtin.command:
    cmd: '{{ __aide_init_command }}'
  when:
    - aide_init_db_enabled | bool
    - not aide_db_check.stat.exists or aide_force_init_enabled | bool
  register: aide_init
  changed_when: aide_init.rc == 0
  async: 3600
  poll: 10

- name: Database | Move new database to production  # noqa: no-handler
  ansible.builtin.command:
    cmd: 'mv {{ __aide_db_new_path }} {{ __aide_db_path }}'
    removes: '{{ __aide_db_new_path }}'
  when:
    - aide_init is changed
  changed_when: true
