---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    podman_enabled: true
    podman_compose_enabled: false
    podman_docker_enabled: false
    podman_podlet_enabled: true
    podman_desktop_enabled: false
    podman_docker_alias_enabled: true
    podman_docker_socket_symlink_enabled: false
    podman_socket_enabled: false
    podman_auto_update_enabled: false
    podman_prune_enabled: true
    podman_prune_schedule: 'weekly'
    podman_prune_all: true
    podman_prune_volumes: true
    podman_registries_search:
      - 'docker.io'
      - 'quay.io'
    podman_short_name_mode: 'permissive'
    podman_tools:
      - 'buildah'
      - 'skopeo'
    podman_firewall_driver: 'firewalld'
    podman_network_backend: 'netavark'
    podman_storage_driver: 'overlay'
    podman_runtime: 'crun'
    podman_log_driver: 'journald'
    podman_default_pids_limit: 2048
    podman_userns_mode: 'auto'
    podman_label: true
    podman_seccomp_enabled: true

  tasks:
    - name: Converge | Include podman role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
