---
# =============================================================================
# RedHat/Fedora-specific variables for auditd
# =============================================================================

__auditd_packages:
  - 'audit'
  - 'audit-libs'

__auditd_remote_packages:
  - 'audispd-plugins'

__auditd_service_name: 'auditd.service'

__auditd_remote_binary: '/sbin/audisp-remote'
