---
- name: Blocklist | Deploy update script
  ansible.builtin.template:
    src: update-blocklist.sh.j2
    dest: '/usr/local/bin/unbound-update-blocklist'
    owner: root
    group: root
    mode: '0755'

- name: Blocklist | Run initial update
  ansible.builtin.command:
    cmd: '/usr/local/bin/unbound-update-blocklist'
    creates: '/etc/unbound/conf.d/blocklist.conf'
  notify: reload unbound

- name: Blocklist | Deploy update systemd service
  ansible.builtin.template:
    src: 'unbound-blocklist.service.j2'
    dest: '/etc/systemd/system/unbound-blocklist.service'
    owner: root
    group: root
    mode: '0644'
  notify: Reload unbound systemd units

- name: Blocklist | Deploy update systemd timer
  ansible.builtin.template:
    src: 'unbound-blocklist.timer.j2'
    dest: '/etc/systemd/system/unbound-blocklist.timer'
    owner: root
    group: root
    mode: '0644'
  notify: Reload unbound systemd units

- name: Blocklist | Enable and start update timer
  ansible.builtin.systemd:
    name: unbound-blocklist.timer
    enabled: true
    state: started
    daemon_reload: true
