---
- name: Configure | Set number of threads
  ansible.builtin.set_fact:
    __unbound_threads: >-
      {{ unbound_num_threads if (unbound_num_threads | int) > 0
         else ansible_facts['processor_vcpus'] | default(1) }}

- name: Configure | Setup unbound-control keys
  ansible.builtin.command:
    cmd: 'unbound-control-setup'
    creates: '/etc/unbound/unbound_control.key'
  when: unbound_remote_control_enabled | bool

- name: Configure | Deploy main configuration
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: '/etc/unbound/unbound.conf'
    owner: root
    group: '{{ __unbound_group }}'
    mode: '0640'
    validate: 'unbound-checkconf %s'
  notify: Restart unbound

- name: Configure | Remove package-provided conf.d files
  ansible.builtin.file:
    path: '/etc/unbound/conf.d/{{ item }}'
    state: absent
  loop:
    - example.com.conf
    - remote-control.conf
    - unbound-local-root.conf
  notify: Restart unbound

- name: Configure | Remove legacy conf.d filenames
  ansible.builtin.file:
    path: '/etc/unbound/conf.d/{{ item }}'
    state: absent
  loop:
    - local-zones.conf
    - forward-zones.conf
  notify: Restart unbound

- name: Configure | Deploy local zones
  ansible.builtin.template:
    src: local-zones.conf.j2
    dest: '/etc/unbound/conf.d/10-local-zones.conf'
    owner: root
    group: '{{ __unbound_group }}'
    mode: '0640'
  notify: Reload unbound
  when: unbound_local_zones | length > 0 or unbound_local_data | length > 0 or unbound_local_data_ptr | length > 0

- name: Configure | Remove local zones config when not needed
  ansible.builtin.file:
    path: '/etc/unbound/conf.d/10-local-zones.conf'
    state: absent
  notify: Reload unbound
  when:
    - unbound_local_zones | length == 0
    - unbound_local_data | length == 0
    - unbound_local_data_ptr | length == 0

- name: Configure | Deploy forward zones
  ansible.builtin.template:
    src: forward-zones.conf.j2
    dest: '/etc/unbound/conf.d/90-forward-zones.conf'
    owner: root
    group: '{{ __unbound_group }}'
    mode: '0640'
  notify: Reload unbound
  when: unbound_forward_zones | length > 0

- name: Configure | Remove forward zones config when not needed
  ansible.builtin.file:
    path: '/etc/unbound/conf.d/90-forward-zones.conf'
    state: absent
  notify: Reload unbound
  when: unbound_forward_zones | length == 0

- name: Configure | Initialize DNSSEC root key
  ansible.builtin.command:
    cmd: 'unbound-anchor -a {{ __unbound_root_key }}'
    creates: '{{ __unbound_root_key }}'
  register: __unbound_anchor
  failed_when:
    - __unbound_anchor.rc != 0
    - __unbound_anchor.rc != 1
  changed_when: __unbound_anchor.rc == 1
  when: unbound_dnssec_enabled | bool
