---
- name: Firewall | Allow OCSP responder port
  ansible.posix.firewalld:
    port: '{{ pki_ocsp_port }}/tcp'
    zone: '{{ pki_firewalld_zone }}'
    permanent: true
    immediate: true
    state: enabled
