---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    avahi_enabled: true

  tasks:
    - name: Converge | Include avahi role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
