---
# =============================================================================
# Podman - Arch Linux Variables
# =============================================================================

__podman_packages:
  - 'podman'
  - 'crun'
  - 'netavark'
  - 'aardvark-dns'
  - 'slirp4netns'
  - 'fuse-overlayfs'
  - 'passt'

__podman_compose_package: 'podman-compose'
__podman_docker_package: 'podman-docker'
__podman_podlet_package: 'podlet'
__podman_desktop_package: 'podman-desktop-bin'

__podman_config_dir: '/etc/containers'
__podman_socket_service: 'podman.socket'
