---
__podman_packages:
  - 'podman'
  - 'crun'
  - 'netavark'
  - 'aardvark-dns'
  - 'slirp4netns'
  - 'fuse-overlayfs'
  - 'passt'

__podman_podlet_package: 'podlet'
__podman_aur_packages:
  desktop:
    - podman-desktop-bin
