---
- name: Install | Logrotate packages
  ansible.builtin.package:
    name: '{{ __logrotate_packages }}'
    state: present
  retries: 3
  delay: 5

- name: Install | Ensure logrotate.d directory exists
  ansible.builtin.file:
    path: '{{ __logrotate_config_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
