---
- name: Firewall | Allow SSH service
  ansible.posix.firewalld:
    service: ssh
    zone: '{{ openssh_firewalld_zone }}'
    permanent: true
    immediate: true
    state: enabled

- name: Firewall | Allow additional SSH ports
  ansible.posix.firewalld:
    port: '{{ item }}/tcp'
    zone: '{{ openssh_firewalld_zone }}'
    permanent: true
    immediate: true
    state: enabled
  loop: '{{ openssh_server_additional_ports }}'
  when: openssh_server_additional_ports | length > 0
