---
- name: Service | Manage OpenSSH service
  ansible.builtin.systemd_service:
    name: '{{ __openssh_service_name }}'
    enabled: "{{ openssh_service_enabled | bool }}"
    state: "{{ openssh_service_enabled | bool | ternary('started', 'stopped') }}"
    daemon_reload: true

- name: Service | Check ssh-agent user service unit state  # noqa: command-instead-of-module
  ansible.builtin.command:
    cmd: 'systemctl --global list-unit-files {{ __openssh_agent_service }}'
  register: __openssh_agent_unit_check
  changed_when: false
  # Unit may not exist on the system
  failed_when: false

- name: Service | Manage global ssh-agent service
  ansible.builtin.systemd_service:
    name: '{{ __openssh_agent_service }}'
    enabled: "{{ openssh_agent_global_service_enabled | bool }}"
    scope: global
  when: "'enabled' in __openssh_agent_unit_check.stdout or 'disabled' in __openssh_agent_unit_check.stdout"
