---
# =============================================================================
# NODE.JS - SYSTEM PACKAGE INSTALLATION
# =============================================================================

- name: Install Package | Install Node.js
  ansible.builtin.package:
    name: '{{ __nodejs_packages }}'
    state: present
