---
- name: Tools | Install rebuild-detector
  ansible.builtin.package:
    name: 'rebuild-detector'
    state: present
  when: pacman_rebuild_detector_enabled | bool

- name: Tools | Install pkgfile
  ansible.builtin.package:
    name: 'pkgfile'
    state: present
  when: pacman_pkgfile_enabled | bool
  notify: 'pkgfile installed'

- name: Tools | Manage pkgfile update timer
  ansible.builtin.systemd_service:
    name: 'pkgfile-update.timer'
    enabled: "{{ pacman_pkgfile_enabled | bool }}"
    state: "{{ pacman_pkgfile_enabled | bool | ternary('started', 'stopped') }}"

- name: Tools | Install informant
  become: true
  become_user: '{{ aur_builder_user }}'
  kewlfft.aur.aur:
    name: 'informant'
    use: '{{ aur_helper }}'
    state: present
  when:
    - pacman_informant_enabled | bool
    - aur_helper | length > 0
