---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    ansible_tools_enabled: true
    ansible_tools_install_ansible: true
    ansible_tools_install_molecule: true
    ansible_tools_install_lint: true

  roles:
    - role: "{{ playbook_dir }}/../../../python"  # noqa: role-name[path]

  tasks:
    - name: Include ansible role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
