---
# NoCOW for log directory

- name: BTRFS | Check filesystem type for log directory
  ansible.builtin.command:
    cmd: "stat -f -c '%T' {{ restic_log_dir }}"
  register: __restic_log_fstype
  changed_when: false
  failed_when: false

- name: BTRFS | Set NoCOW on log directory
  ansible.builtin.command:
    cmd: "chattr +C {{ restic_log_dir }}"
  when:
    - __restic_log_fstype.stdout | default('') == 'btrfs'
  changed_when: false
