---
- name: Jobs | Create backup scripts
  ansible.builtin.template:
    src: backup.sh.j2
    dest: '{{ restic_script_dir }}/restic-backup-{{ item.name }}'
    owner: '{{ restic_user }}'
    group: '{{ restic_group }}'
    mode: '0750'
  loop: '{{ restic_jobs }}'
  loop_control:
    label: '{{ item.name }}'

- name: Jobs | Create systemd service units
  ansible.builtin.template:
    src: backup.service.j2
    dest: '/etc/systemd/system/restic-backup-{{ item.name }}.service'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ restic_jobs }}'
  loop_control:
    label: '{{ item.name }}'
  notify: Reload restic systemd units

- name: Jobs | Create systemd timer units
  ansible.builtin.template:
    src: backup.timer.j2
    dest: '/etc/systemd/system/restic-backup-{{ item.name }}.timer'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ restic_jobs }}'
  loop_control:
    label: '{{ item.name }}'
  notify: Reload restic systemd units
