---
# marcstraube.common.apparmor/molecule/default/converge.yml

- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: Include apparmor role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
