---
# =============================================================================
# Avahi - Configuration Tasks
# =============================================================================

- name: Configure | Deploy avahi-daemon configuration
  ansible.builtin.template:
    src: 'avahi-daemon.conf.j2'
    dest: '{{ __avahi_config_file }}'
    owner: root
    group: root
    mode: '0644'
  notify: Restart avahi

- name: Configure | Ensure mdns_minimal in nsswitch.conf
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: '{{ avahi_nsswitch_hosts }}'
    backup: true
  when: avahi_nss_mdns | bool
  notify: Restart avahi
