---
- name: Main | Handle deprecated variables
  ansible.builtin.set_fact:
    avahi_nss_mdns_enabled: >-
      {{ avahi_nss_mdns | default(avahi_nss_mdns_enabled) | bool }}
  when: avahi_nss_mdns is defined
  tags:
    - avahi

- name: Main | Load OS-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["os_family"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      paths:
        - 'vars'
  tags:
    - avahi

- name: Main | Import install tasks
  ansible.builtin.import_tasks: install.yml
  when: avahi_enabled | bool
  tags:
    - avahi
    - avahi:install

- name: Main | Import configure tasks
  ansible.builtin.import_tasks: configure.yml
  when: avahi_enabled | bool
  tags:
    - avahi
    - avahi:configure

- name: Main | Import service tasks
  ansible.builtin.import_tasks: service.yml
  when: avahi_enabled | bool
  tags:
    - avahi
    - avahi:service

- name: Main | Include firewall tasks
  ansible.builtin.include_tasks:
    file: firewall.yml
    apply:
      tags:
        - avahi
        - avahi:firewall
  when:
    - avahi_enabled | bool
    - avahi_firewalld_enabled | bool
  tags:
    - avahi
    - avahi:firewall

- name: Main | Include AppArmor tasks
  ansible.builtin.include_tasks:
    file: apparmor.yml
    apply:
      tags:
        - avahi
        - avahi:apparmor
  when:
    - avahi_enabled | bool
    - avahi_apparmor_enabled | bool
    - ansible_facts['os_family'] != 'RedHat'
  tags:
    - avahi
    - avahi:apparmor
