---
- name: Service | Manage avahi service
  ansible.builtin.systemd_service:
    name: '{{ __avahi_service_name }}'
    enabled: "{{ avahi_service_enabled | bool }}"
    state: "{{ avahi_service_enabled | bool | ternary('started', 'stopped') }}"
