---
# =============================================================================
# Avahi - Service Tasks
# =============================================================================

- name: Service | Enable and start avahi
  ansible.builtin.systemd:
    name: '{{ __avahi_service_name }}'
    enabled: true
    state: started
  when: avahi_enabled | bool

- name: Service | Stop and disable avahi
  ansible.builtin.systemd:
    name: '{{ __avahi_service_name }}'
    enabled: false
    state: stopped
  when: not (avahi_enabled | bool)
