---
- name: Service | Enable podman socket
  ansible.builtin.systemd:
    name: '{{ __podman_socket_service }}'
    enabled: true
    state: started
  when: podman_socket_enabled | bool

- name: Service | Disable podman socket when not needed
  ansible.builtin.systemd:
    name: '{{ __podman_socket_service }}'
    enabled: false
    state: stopped
  when: not (podman_socket_enabled | bool)
  failed_when: false

- name: Service | Enable podman auto-update timer
  ansible.builtin.systemd:
    name: 'podman-auto-update.timer'
    enabled: true
    state: started
  when: podman_auto_update_enabled | bool

- name: Service | Disable podman auto-update timer when not needed
  ansible.builtin.systemd:
    name: 'podman-auto-update.timer'
    enabled: false
    state: stopped
  when: not (podman_auto_update_enabled | bool)
  failed_when: false

- name: Service | Deploy system prune timer
  ansible.builtin.template:
    src: podman-prune.timer.j2
    dest: '/etc/systemd/system/podman-prune.timer'
    owner: root
    group: root
    mode: '0644'
  when: podman_prune_enabled | bool
  notify: 'reload podman systemd units'

- name: Service | Deploy system prune service
  ansible.builtin.template:
    src: podman-prune.service.j2
    dest: '/etc/systemd/system/podman-prune.service'
    owner: root
    group: root
    mode: '0644'
  when: podman_prune_enabled | bool
  notify: 'reload podman systemd units'

- name: Service | Enable system prune timer
  ansible.builtin.systemd:
    name: 'podman-prune.timer'
    enabled: true
    state: started
    daemon_reload: true
  when: podman_prune_enabled | bool

- name: Service | Disable system prune timer when not needed
  ansible.builtin.systemd:
    name: 'podman-prune.timer'
    enabled: false
    state: stopped
  when: not (podman_prune_enabled | bool)
  failed_when: false

- name: Service | Remove prune units when disabled
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - '/etc/systemd/system/podman-prune.timer'
    - '/etc/systemd/system/podman-prune.service'
  when: not (podman_prune_enabled | bool)
  notify: 'reload podman systemd units'
