---
- name: Service | Manage auditd service
  ansible.builtin.systemd_service:
    name: '{{ __auditd_service_name }}'
    enabled: "{{ auditd_service_enabled | bool }}"
    state: "{{ auditd_service_enabled | bool | ternary('started', 'stopped') }}"
    daemon_reload: true
