---
#
# RedHat Variables
#
# Targets the newest supported EL major. See RedHat-9.yml for EL9.
#

# Version control
__git_packages:
  - 'git'

__git_lfs_package: 'git-lfs'
__git_github_cli_package: 'gh'
__git_gitlab_cli_package: ''  # not in EPEL 9/10
