---
- name: Service | Manage AppArmor service
  ansible.builtin.systemd_service:
    name: '{{ __apparmor_service_name }}'
    enabled: "{{ apparmor_service_enabled | bool }}"
    state: "{{ apparmor_service_enabled | bool | ternary('started', 'stopped') }}"
    daemon_reload: true
