---
# =============================================================================
# RHEL/Fedora/Rocky-specific variables for sudo
# =============================================================================

__sudo_package: 'sudo'
__sudo_group: 'wheel'
