---
__clamav_packages:
  - 'clamav'
__clamav_milter_packages: []  # milter binary included in clamav package
__clamav_daemon_service: 'clamav-daemon.service'
__clamav_freshclam_service: 'clamav-freshclam.service'
__clamav_milter_service: ''  # no systemd unit on Arch
__clamav_config_dir: '/etc/clamav'
__clamav_daemon_config_file: '/etc/clamav/clamd.conf'
__clamav_freshclam_config_file: '/etc/clamav/freshclam.conf'
__clamav_milter_config_file: '/etc/clamav/clamav-milter.conf'
__clamav_user: 'clamav'
__clamav_group: 'clamav'
__clamav_apparmor_profile: 'usr.sbin.clamd'
