---
# =============================================================================
# Archlinux specific variables
# =============================================================================

__ansible_tools_ansible_packages:
  - 'ansible'

__ansible_tools_molecule_packages:
  - 'molecule'

__ansible_tools_aur_packages:
  # Requires --nocheck due to upstream test bug
  molecule:
    - molecule-plugins
  podman:
    - python-podman

__ansible_tools_docker_packages:
  - 'python-docker'

__ansible_tools_lint_packages:
  - 'ansible-lint'
  - 'yamllint'
