---
- name: SSH Keys | Add SSH authorized keys
  ansible.posix.authorized_key:
    user: '{{ item.name }}'
    key: "{{ item.ssh_keys | join('\n') }}"
    state: present
    exclusive: '{{ item.ssh_keys_exclusive | default(false) }}'
    path: >-
      {{ item.home | default(users_default_home_base + "/" + item.name) }}/{{
        users_ssh_authorized_keys_dir }}/{{ users_ssh_authorized_keys_file }}
    manage_dir: false
  loop: '{{ users_list | selectattr("ssh_keys", "defined") | list }}'
  loop_control:
    label: '{{ item.name }}'
  when:
    - item.state | default('present') == 'present'
    - item.ssh_keys | length > 0

- name: SSH Keys | Set authorized_keys file permissions
  ansible.builtin.file:
    path: >-
      {{ item.home | default(users_default_home_base + "/" + item.name) }}/{{
        users_ssh_authorized_keys_dir }}/{{ users_ssh_authorized_keys_file }}
    owner: '{{ item.name }}'
    group: '{{ item.group | default(item.name) }}'
    mode: '{{ users_ssh_authorized_keys_mode }}'
  loop: '{{ users_list }}'
  loop_control:
    label: '{{ item.name }}'
  when:
    - item.state | default('present') == 'present'
    - item.ssh_keys is defined
    - item.ssh_keys | length > 0

#
# Key File Deployment
#

- name: SSH Keys | Deploy private key files
  ansible.builtin.copy:
    src: '{{ inventory_dir }}/files/ssh/{{ item.1.src }}'
    dest: >-
      {{ item.0.home | default(users_default_home_base + "/" + item.0.name) }}/{{
        users_ssh_authorized_keys_dir }}/{{ item.1.dest }}
    owner: '{{ item.0.name }}'
    group: '{{ item.0.group | default(item.0.name) }}'
    mode: '{{ item.1.mode | default(users_ssh_key_file_mode) }}'
  loop: '{{ users_list | subelements("ssh_key_files", skip_missing=True) }}'
  loop_control:
    label: '{{ item.0.name }}: {{ item.1.dest }}'
  when: item.0.state | default('present') == 'present'
  no_log: true

- name: SSH Keys | Deploy public key files
  ansible.builtin.copy:
    src: '{{ inventory_dir }}/files/ssh/{{ item.1.src_public }}'
    dest: >-
      {{ item.0.home | default(users_default_home_base + "/" + item.0.name) }}/{{
        users_ssh_authorized_keys_dir }}/{{ item.1.dest }}.pub
    owner: '{{ item.0.name }}'
    group: '{{ item.0.group | default(item.0.name) }}'
    mode: '{{ users_ssh_public_key_file_mode }}'
  loop: '{{ users_list | subelements("ssh_key_files", skip_missing=True) }}'
  loop_control:
    label: '{{ item.0.name }}: {{ item.1.dest }}.pub'
  when:
    - item.0.state | default('present') == 'present'
    - item.1.src_public is defined
