---
- name: Install | sysctl packages
  ansible.builtin.package:
    name: '{{ __sysctl_packages }}'
    state: present
  retries: 3
  delay: 5

- name: Install | Load br_netfilter module for Docker profile
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present
  when: sysctl_profile_docker_enabled | bool
