---
galaxy_info:
  author: 'Marc Straube'
  description: 'Install and configure Lynis for automated security auditing'
  license: 'MIT'
  min_ansible_version: '2.17'

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - all

  galaxy_tags:
    - lynis
    - security
    - audit
    - hardening
    - compliance

dependencies: []
