---
- name: Update rkhunter database
  ansible.builtin.command:
    cmd: rkhunter --propupd
  changed_when: true
  when: rkhunter_enabled | bool

- name: Reload rkhunter systemd units
  ansible.builtin.systemd_service:
    daemon_reload: true
  # Container-safety for molecule
  failed_when: false
  when: rkhunter_enabled | bool

- name: Restart rkhunter timer
  ansible.builtin.systemd_service:
    name: '{{ __rkhunter_timer_name }}'
    state: restarted
  when: rkhunter_timer_enabled | bool
