---
#
# Backports (Debian only)
#

- name: Repos | Enable Debian Backports
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_facts['distribution_release'] }}-backports main contrib non-free"
    state: present
    filename: 'backports'
  retries: 5
  delay: 10
  when:
    - apt_backports_enabled | bool
    - ansible_facts['distribution'] == 'Debian'
  notify: 'apt configuration changed'

#
# PPAs (Ubuntu only)
#

- name: Repos | Add PPAs
  ansible.builtin.apt_repository:
    repo: '{{ item }}'
    state: present
  retries: 5
  delay: 10
  loop: '{{ apt_ppas }}'
  when:
    - apt_ppas | length > 0
    - ansible_facts['distribution'] == 'Ubuntu'
  notify: 'apt configuration changed'

#
# Custom Repositories
#

- name: Repos | Add custom repository GPG keys
  ansible.builtin.get_url:
    url: '{{ item.gpg_key }}'
    dest: '/etc/apt/keyrings/{{ item.name }}.asc'
    owner: root
    group: root
    mode: '0644'
  retries: 5
  delay: 10
  loop: '{{ apt_custom_repos }}'
  loop_control:
    label: '{{ item.name }}'
  when:
    - apt_custom_repos | length > 0
    - item.gpg_key is defined

- name: Repos | Add custom repositories
  ansible.builtin.apt_repository:
    repo: '{{ item.repo }}'
    state: present
    filename: '{{ item.name }}'
  retries: 5
  delay: 10
  loop: '{{ apt_custom_repos }}'
  loop_control:
    label: '{{ item.name }}'
  when: apt_custom_repos | length > 0
  notify: 'apt configuration changed'

- name: Repos | Flush handlers to update apt cache
  ansible.builtin.meta: flush_handlers
