---
- name: Tools | Install apt-file
  ansible.builtin.package:
    name: 'apt-file'
    state: present
  when: apt_apt_file_enabled | bool
  notify: 'apt-file installed'

- name: Tools | Install needrestart
  ansible.builtin.package:
    name: 'needrestart'
    state: present
  when: apt_needrestart_enabled | bool

- name: Tools | Configure needrestart mode
  ansible.builtin.lineinfile:
    path: '/etc/needrestart/needrestart.conf'
    regexp: "^#?\\$nrconf\\{restart\\}"
    line: "$nrconf{restart} = '{{ apt_needrestart_mode }}';"
    owner: root
    group: root
    mode: '0644'
  when: apt_needrestart_enabled | bool

- name: Tools | Install debsums
  ansible.builtin.package:
    name: 'debsums'
    state: present
  when: apt_debsums_enabled | bool

- name: Tools | Install debian-goodies
  ansible.builtin.package:
    name: 'debian-goodies'
    state: present
  when: apt_debian_goodies_enabled | bool
