---
- name: Tools | Install apt-file for command-not-found
  ansible.builtin.apt:
    name: apt-file
    state: present
  when: apt_install_apt_file | bool
  notify: 'apt-file installed'

- name: Tools | Install needrestart
  ansible.builtin.apt:
    name: needrestart
    state: present
  when: apt_install_needrestart | bool

- name: Tools | Configure needrestart mode
  ansible.builtin.lineinfile:
    path: '/etc/needrestart/needrestart.conf'
    regexp: "^#?\\$nrconf\\{restart\\}"
    line: "$nrconf{restart} = '{{ apt_needrestart_mode }}';"
    owner: root
    group: root
    mode: '0644'
  when: apt_install_needrestart | bool

- name: Tools | Install debsums for package integrity checking
  ansible.builtin.apt:
    name: debsums
    state: present
  when: apt_install_debsums | bool

- name: Tools | Install debian-goodies
  ansible.builtin.apt:
    name: debian-goodies
    state: present
  when: apt_install_debian_goodies | bool
