---
__pam_hardening_packages:
  - libpam-modules
  - libpam-runtime

__pam_hardening_pwquality_package: 'libpam-pwquality'

__pam_hardening_google_authenticator_package: 'libpam-google-authenticator'
