---
# =============================================================================
# RedHat/Rocky variables for rkhunter
# =============================================================================

__rkhunter_package: 'rkhunter'
__rkhunter_scriptdir: '/usr/share/rkhunter/scripts'
__rkhunter_pkgmgr: 'RPM'
