---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    rkhunter_enabled: true
    rkhunter_update_on_install: false
    rkhunter_timer_enabled: true
    rkhunter_mail_on_warning: ''
    rkhunter_allowhiddendir:
      - '/dev/.udev'

  tasks:
    - name: Include rkhunter role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
