---
- name: Service | Manage chrony service
  ansible.builtin.systemd_service:
    name: '{{ __chrony_service_name }}'
    enabled: "{{ chrony_service_enabled | bool }}"
    state: "{{ chrony_service_enabled | bool | ternary('started', 'stopped') }}"
