---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    nodejs_enabled: true
    # Arch will auto-fallback to 'package'
    nodejs_install_method: 'nodesource'
    nodejs_version: '24'
    nodejs_package_managers:
      - yarn

  tasks:
    - name: Include nodejs role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
