---
- name: Service | Enable and start fail2ban service
  ansible.builtin.systemd:
    name: '{{ __fail2ban_service_name }}'
    enabled: true
    state: started
  when: fail2ban_enabled | bool

- name: Service | Stop and disable fail2ban service
  ansible.builtin.systemd:
    name: '{{ __fail2ban_service_name }}'
    enabled: false
    state: stopped
  when: not (fail2ban_enabled | bool)
