---
- name: Service | Manage fail2ban service
  ansible.builtin.systemd_service:
    name: '{{ __fail2ban_service_name }}'
    enabled: "{{ fail2ban_service_enabled | bool }}"
    state: "{{ fail2ban_service_enabled | bool | ternary('started', 'stopped') }}"
    daemon_reload: true
