---
- name: Reinitialize AIDE database
  ansible.builtin.command:
    cmd: '{{ __aide_init_command }}'
  register: aide_reinit
  changed_when: aide_reinit.rc == 0
  async: 3600
  poll: 10
  listen: Reinitialize AIDE database

- name: Move new database to production after reinit
  ansible.builtin.command:
    cmd: >-
      mv {{ aide_database_new }}{{ '.gz' if aide_database_format == 'gzip' else '' }}
      {{ aide_database }}{{ '.gz' if aide_database_format == 'gzip' else '' }}
    removes: '{{ aide_database_new }}{{ ".gz" if aide_database_format == "gzip" else "" }}'
  when: aide_reinit is changed
  changed_when: true
  listen: Reinitialize AIDE database

- name: Reload aide systemd units
  ansible.builtin.systemd:
    daemon_reload: true
  failed_when: false
  listen: Reload aide systemd units

- name: Restart AIDE timer
  ansible.builtin.systemd:
    name: aide-check.timer
    state: restarted
  listen: Restart AIDE timer
  when: aide_timer_enabled | bool
