---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    mta_enabled: true
    mta_relayhost: ''
    mta_mydomain: 'example.test'

  tasks:
    - name: Converge | Include mta role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
