---
- name: Main | Import install tasks
  ansible.builtin.import_tasks: install.yml
  when: firejail_enabled | bool
  tags: [firejail, firejail:install]

- name: Main | Import configure tasks
  ansible.builtin.import_tasks: configure.yml
  when: firejail_enabled | bool
  tags: [firejail, firejail:configure]
