---
- name: Service | Enable and start firewalld
  ansible.builtin.systemd:
    name: '{{ __firewalld_service_name }}'
    enabled: true
    state: started
  when: firewalld_enabled | bool

- name: Service | Stop and disable firewalld
  ansible.builtin.systemd:
    name: '{{ __firewalld_service_name }}'
    enabled: false
    state: stopped
  when: not (firewalld_enabled | bool)
