---
- name: Service | Manage firewalld service
  ansible.builtin.systemd_service:
    name: '{{ __firewalld_service_name }}'
    enabled: "{{ firewalld_service_enabled | bool }}"
    state: "{{ firewalld_service_enabled | bool | ternary('started', 'stopped') }}"
    daemon_reload: true
