---
# =============================================================================
# Sysctl - RedHat/Fedora Variables
# =============================================================================

__sysctl_packages:
  - 'procps-ng'
