---
- name: Locale | Install locale source data (RedHat)
  ansible.builtin.package:
    name: '{{ __base_locale_packages }}'
    state: present
  retries: 3
  delay: 5
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - __base_locale_packages is defined

- name: Locale | Configure locale.gen
  ansible.builtin.lineinfile:
    path: '/etc/locale.gen'
    regexp: '^#?{{ item | regex_escape }}'
    line: '{{ item }}'
    state: present
  loop: '{{ base_locales }}'
  notify: 'generate locales'
  when: ansible_facts['os_family'] in ['Archlinux', 'Debian']

- name: Locale | Configure locale.conf
  ansible.builtin.template:
    src: 'locale.conf.j2'
    dest: '/etc/locale.conf'
    owner: root
    group: root
    mode: '0644'
  notify: 'generate locales'

- name: Locale | Flush handlers to generate locales
  ansible.builtin.meta: flush_handlers
