---
- name: Systemd | Ensure journald.conf.d directory exists
  ansible.builtin.file:
    path: '/etc/systemd/journald.conf.d'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Systemd | Ensure coredump.conf.d directory exists
  ansible.builtin.file:
    path: '/etc/systemd/coredump.conf.d'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Systemd | Configure journald
  ansible.builtin.template:
    src: 'journald.conf.j2'
    dest: '/etc/systemd/journald.conf.d/ansible.conf'
    owner: root
    group: root
    mode: '0644'
  notify: 'restart journald'

- name: Systemd | Configure coredump
  ansible.builtin.template:
    src: 'coredump.conf.j2'
    dest: '/etc/systemd/coredump.conf.d/ansible.conf'
    owner: root
    group: root
    mode: '0644'

- name: Systemd | Enable services
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    enabled: true
    state: started
  loop: '{{ base_services_enabled }}'

- name: Systemd | Disable services
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    enabled: false
    state: stopped
  loop: '{{ base_services_disabled }}'
  # Service may not be installed on the system
  failed_when: false
