---
- name: Configure | Reset FPM reload list
  ansible.builtin.set_fact:
    __php_fpm_changed_services: []

- name: Configure | PHP versions
  ansible.builtin.include_tasks:
    file: configure_version.yml
    apply:
      tags:
        - php
        - php:configure
  loop: '{{ php_versions }}'
  loop_control:
    loop_var: __php_config_item
  tags:
    - php
    - php:configure
