---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    gnupg_enabled: true
    gnupg_gui_enabled: false
    gnupg_tools_enabled: false
    gnupg_agent_ssh_enabled: true
    gnupg_agent_allow_preset_passphrase: true
    gnupg_no_greeting: true
    gnupg_throw_keyids: false
    gnupg_dirmngr_resolver_timeout: 15
    gnupg_users:
      - username: root
        mode: 'managed'
        agent_ssh: false
      - username: testuser
        mode: 'managed'
        agent_ssh: true
      - username: disableduser
        mode: 'disabled'
        agent_ssh: false

  pre_tasks:
    - name: Converge | Create test user
      ansible.builtin.user:
        name: testuser
        state: present
        create_home: true

    - name: Converge | Create disabled test user
      ansible.builtin.user:
        name: disableduser
        state: present
        create_home: true

  tasks:
    - name: Converge | Include gnupg role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
