---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: Create test user
      ansible.builtin.user:
        name: testuser
        state: present
        create_home: true

    - name: Create disabled test user
      ansible.builtin.user:
        name: disableduser
        state: present
        create_home: true

  vars:
    gnupg_enabled: true
    gnupg_install_gui: false
    gnupg_install_tools: false
    gnupg_agent_enable_ssh: true
    gnupg_agent_allow_preset_passphrase: true
    gnupg_no_greeting: true
    gnupg_throw_keyids: false
    gnupg_dirmngr_resolver_timeout: 15
    gnupg_users:
      - username: root
        mode: 'managed'
        agent_ssh: false
      - username: testuser
        mode: 'managed'
        agent_ssh: true
      - username: disableduser
        mode: 'disabled'
        agent_ssh: false

  tasks:
    - name: Include gnupg role  # noqa: role-name[path]
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}/../..'
