---
- name: Configure | Deploy WireGuard configuration
  ansible.builtin.template:
    src: wg.conf.j2
    dest: '{{ wireguard_config_dir }}/{{ __wireguard_iface.name }}.conf'
    owner: root
    group: root
    mode: '{{ __wireguard_iface.config_mode | default("0600") }}'
  register: __wireguard_config_changed
  no_log: true

- name: Configure | Restart WireGuard service
  ansible.builtin.systemd_service:
    name: 'wg-quick@{{ __wireguard_iface.name }}'
    state: restarted
  when:
    - __wireguard_config_changed is changed
    - wireguard_service_enabled | bool
