---
# =============================================================================
# WireGuard - Firewall Tasks
# =============================================================================

- name: Firewall | Open WireGuard port
  ansible.posix.firewalld:
    port: '{{ wireguard_port }}/udp'
    zone: '{{ wireguard_firewalld_zone }}'
    permanent: true
    immediate: true
    state: enabled

- name: Firewall | Add WireGuard interface to trusted zone
  ansible.posix.firewalld:
    interface: '{{ wireguard_interface }}'
    zone: 'trusted'
    permanent: true
    immediate: true
    state: enabled

- name: Firewall | Enable masquerading for server mode
  ansible.posix.firewalld:
    masquerade: true
    zone: '{{ wireguard_firewalld_zone }}'
    permanent: true
    immediate: true
    state: enabled
  when: wireguard_server_mode | bool
