---
- name: Install | WireGuard packages
  ansible.builtin.package:
    name: '{{ __wireguard_packages }}'
    state: present
  retries: 3
  delay: 5

- name: Install | Load WireGuard kernel module
  community.general.modprobe:
    name: '{{ __wireguard_kernel_module }}'
    state: present
    persistent: present

- name: Install | Ensure config directory exists
  ansible.builtin.file:
    path: '{{ wireguard_config_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Install | Enable IP forwarding (IPv4)
  ansible.posix.sysctl:
    name: 'net.ipv4.ip_forward'
    value: '1'
    state: present
    sysctl_set: true
    reload: true
  when: wireguard_ip_forward_enabled | bool

- name: Install | Enable IP forwarding (IPv6)
  ansible.posix.sysctl:
    name: 'net.ipv6.conf.all.forwarding'
    value: '1'
    state: present
    sysctl_set: true
    reload: true
  when:
    - wireguard_ip_forward_enabled | bool
    - wireguard_address_ipv6 | length > 0
