---
- name: Main | Load OS-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["os_family"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      paths:
        - 'vars'
  tags:
    - wireguard

- name: Main | Import install tasks
  ansible.builtin.import_tasks: install.yml
  when: wireguard_enabled | bool
  tags:
    - wireguard
    - wireguard:install

- name: Main | Include per-interface tasks
  ansible.builtin.include_tasks:
    file: interface.yml
    apply:
      tags:
        - wireguard
  loop: '{{ wireguard_interfaces }}'
  loop_control:
    loop_var: __wireguard_iface
    label: '{{ __wireguard_iface.name }}'
  when: wireguard_enabled | bool
  tags:
    - wireguard
