---
- name: Service | Manage WireGuard service
  ansible.builtin.systemd_service:
    name: 'wg-quick@{{ __wireguard_iface.name }}'
    enabled: '{{ wireguard_service_enabled | bool }}'
    state: "{{ wireguard_service_enabled | bool | ternary('started', 'stopped') }}"
    daemon_reload: true
