---
# Rocky 9 bundles unbound-anchor in the main unbound package.

__unbound_packages:
  - 'unbound'

__unbound_service_name: 'unbound.service'
__unbound_user: 'unbound'
__unbound_group: 'unbound'

__unbound_root_key: '/var/lib/unbound/root.key'
__unbound_tls_cert_bundle: '/etc/pki/tls/certs/ca-bundle.crt'
