---
#
# Power Profiles Daemon
#

__energy_management_ppd_packages:
  - 'power-profiles-daemon'
  - 'python-gobject'
__energy_management_ppd_service: 'power-profiles-daemon.service'

#
# Battery (tp_smapi for older ThinkPads)
#

__energy_management_tp_smapi_packages:
  - 'tp_smapi'
